name: web_cloner
description: "Web Cloner - Desktop application for cloning websites and generating screenshots"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  http: ^1.4.0
  html: ^0.15.4
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.1.2
  uuid: ^4.4.0
  file_picker: ^8.0.6
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.3.1
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2+4
  screenshot: ^2.1.0
  url_launcher: ^6.3.0
  intl: ^0.20.2
  flutter_smart_dialog: ^4.9.2
  remixicon: ^1.4.1
  # puppeteer: ^3.19.0
  puppeteer:
    path: packages/puppeteer
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_config.yaml
    - assets/chrome-win/
    - assets/chrome-win/locales/
    - assets/chrome-win/MEIPreload/
    - assets/chrome-win/PrivacySandboxAttestationsPreloaded/
    - assets/chrome-win/IwaKeyDistribution/
